### PR TITLE
Italian locale

### PR DESCRIPTION
**Pull request by stefanop1**
Adding Italian locate

### CODE REVIEW

**Comment by stefanop1** [comment]
I really like this package. I wish to add the Italian locale.

**Comment by tejainece** [comment]
Thanks for the contribution. I will merge it and publish to pub.

**Comment by stefanop1** [comment]
Pardon me,
I am not an expert on this.
There will be a new version on the pub soon?
Stefano

**Comment by tejainece** [comment]
Yes. I have published it as `2.0.11`.

**Comment by stefanop1** [comment]
Perfect, thanks, Stefano

**Pull request merged**
